### ISSUE TITLE
curl_cffi.curl.CurlError: Failed to perform, ErrCode: 28, Reason: 'Operation timed out after 30002 milliseconds with 0 bytes received'

### ISSUE THREAD

**Issue by wsweishang** [xcscxr/ouo-bypass#8]
**URL**
https://ouo.io/MhI7WZ

**ERROR：**
Traceback (most recent call last):
  File "C:\Users\Thinkpad\AppData\Local\Programs\Python\Python39\lib\site-packages\curl_cffi\requests\session.py", line 436, in request
    c.perform()
  File "C:\Users\Thinkpad\AppData\Local\Programs\Python\Python39\lib\site-packages\curl_cffi\curl.py", line 191, in perform
    self._check_error(ret, action="perform")
  File "C:\Users\Thinkpad\AppData\Local\Programs\Python\Python39\lib\site-packages\curl_cffi\curl.py", line 84, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, ErrCode: 28, Reason: 'Operation timed out after 30002 milliseconds with 0 bytes received'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\private file\cache\Eclipse\python_script_practice\web_crawler_download\ouo_bypass_v1.py", line 87, in <module>
    out = ouo_bypass(url)
  File "D:\private file\cache\Eclipse\python_script_practice\web_crawler_download\ouo_bypass_v1.py", line 60, in ouo_bypass
    res = client.get(tempurl, impersonate="chrome110")
  File "C:\Users\Thinkpad\AppData\Local\Programs\Python\Python39\lib\site-packages\curl_cffi\requests\session.py", line 438, in request
    raise RequestsError(e)
curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 28, Reason: 'Operation timed out after 30002 milliseconds with 0 bytes received'

![Uploading 1694747516387.png…]()

**Comment by xcscxr** [comment]
Issue with your network connectivity or vpn/firewall/proxy.
Maybe take a moment to carefully consider the content before posting any links.
